# Generated by Django 4.2.4 on 2024-03-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='name_of_institute',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='state',
            new_name='temporary_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fee_receipt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(choices=[('Singing', 'singing'), ('Dancing', 'dancing'), ('Painting', 'painting'), ('Hiking', 'hiking'), ('Gaming', 'gaming'), ('Cooking', 'cooking'), ('Sports', 'sports')], default='Singing', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_picture/'),
        ),
    ]
