# Generated by Django 5.0.1 on 2024-03-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='seater2',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='seater3',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
